config/routes.rb
GuyWho::Application.routes.draw do
  root :to => 'players#search_page'

  resources :players do
    collection do
      get 'search_page'
      get 'search'
      get 'get_info'
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :number, :position, :team_name, :team_city, :url
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :number, :presence => true
  validates :position, :presence => true
  validates :team_name, :presence => true
  validates :team_city, :presence => true
  validates :url, :presence => true

  # TODO: downcase
  searchable do
    text :first_name do
      self.first_name.downcase
    end
    text :last_name do
      self.last_name.downcase
    end
    text :team_name do
      self.team_name.downcase
    end
    text :team_city do
      self.team_city.downcase
    end
    text :number do
      self.number.to_s
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/players_controller.rb
require 'nokogiri'
require 'open-uri'

class PlayersController < ApplicationController
  include PlayersHelper

  def show
    @player = Player.find_by_id(params[:id])
  end

  # render json given a query
  def search
    # Get param "query", parse query into tokens, and find relevant players
    players = nil
    query = params[:query]
    
    if query != nil
      # TODO: downcase
      # parse query
      query_terms = query.downcase.strip.split(/\s+/)

      # construct full query string
      query_string = ''
      query_terms.each do |term|
        if term[0] == '#'
          term = term[1..-1]
        end
        query_string += ('first_name_text:'+ term +'~0.5 OR ')
        query_string += ('last_name_text:'+ term +'~0.5 OR ')
        query_string += ('team_name_text:'+ term +'~0.5 OR ')
        query_string += ('team_city_text:'+ term +'~0.5 OR ')
        query_string += ('number_text:'+ term +'~0.5 OR ')
      end
      query_string = query_string[0..-4] # cut last ' OR '
      
      # assign query string and get results
      players = Player.search do
        adjust_solr_params do |params|
          params[:q] = query_string;
          params[:defType] = 'lucene'
        end
      end.results
    end
    
    render :json => players
  end

  def search_page
  end

  def get_info
    id = params[:id]
    player = Player.find_by_id(id)
    # Handle wrong id
    if id == nil or player == nil
      render :text => 'Not Found', :status => 503
    end

    # Found player
    doc = Nokogiri::HTML(open(player.url))
    stats = doc.css('dl#prastats dd')
    ppg = stats[0].text.strip()
    rpg = stats[1].text.strip()
    apg = stats[2].text.strip()
    name_url = ''
    if player.url =~ /http:\/\/www.nba.com\/playerfile\/(.+)\//
      name_url = $1
    end
    imgurl = 'http://i.cdn.turner.com/nba/nba/media/act_'+name_url+'.jpg'

    # Get news
    news = getNews("#{player.first_name} #{player.last_name}")

    info = {:ppg => ppg, :rpg => rpg, :apg => apg, :img => imgurl, :news => news}

    render :json => info
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
require "net/https"
require "uri"
require "json"

module PlayersHelper
  def getNews(query)
    url = URI::encode("https://ajax.googleapis.com/ajax/services/search/news?v=1.0&q=#{query}")
    uri = URI.parse(url)

    # Set http object, using ssl
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    # Send request and get results
    request = Net::HTTP::Get.new(uri.request_uri)
    response = http.request(request)
    results = JSON.parse(response.body)["responseData"]["results"]
    results = results.map do |news|
      {:url => news["unescapedUrl"], :title => news["titleNoFormatting"]}
    end
    return results
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuyWho</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/search1.html.erb
<% if not @players.empty? %>
  <% @players.each do |player| %>
    <h1><%= player.first_name + " " + player.last_name %><h1>
  <% end %>
<% end %>

app/views/players/search_page.html.erb
<div class="container">
  <center><br><h3>Looking for a player?</h3></center>
  <%= form_tag(search_players_path, :method => "get", :id => "search_box") do %>
    <%= text_field_tag(:query, nil, :placeholder => "Harden Houston, Clippers #32, Thunders sefolosaaaaa...") %>
    <%= submit_tag("Search", :id => "search_button") %>
  <% end %>

  <div class="row">
    <div class="span1"></div>
    <div class="span4">
      <div id="results_container"><ul class="nav nav-pills nav-stacked" id="results"></ul></div>
    </div>
    <div class="span1"></div>
    <div class="span5">
      <div id="information_container"><div id="information"></div></div>
    </div>
  </div>
</div>

<script>initSearchPage();</script>

app/views/players/show.html.erb
<% if @player != nil %>
  <h1><%= @player.first_name+" "+@player.last_name %></h1>

<% else %>
  <h1>Player not found!</h1>
<% end %>